### ISSUE TITLE
Credential Generator Issues

### ISSUE THREAD

**Issue by BrunoCoimbra** [glideinWMS/glideinwms#207]
**Describe the bug**
Mats reported issues using credentials generators. When using them, he sees the following error message on the group logs:

```
[2022-08-26 15:51:32,061] WARNING: Credential file /etc/gwms-frontend/plugin.d/scitokens_callout.py is expired, skipping 
[2022-08-26 15:51:32,062] ERROR: Invalid header padding 
Traceback (most recent call last): 
 File "/usr/lib/python3.6/site-packages/jwt/api_jws.py", line 172, in _load 
   header_data = base64url_decode(header_segment) 
 File "/usr/lib/python3.6/site-packages/jwt/utils.py", line 42, in base64url_decode 
   return base64.urlsafe_b64decode(input) 
 File "/usr/lib64/python3.6/base64.py", line 133, in urlsafe_b64decode 
   return b64decode(s) 
 File "/usr/lib64/python3.6/base64.py", line 87, in b64decode 
   return binascii.a2b_base64(s) 
binascii.Error: Incorrect padding 

During handling of the above exception, another exception occurred: 

Traceback (most recent call last): 
 File "/usr/lib/python3.6/site-packages/glideinwms/lib/token_util.py", line 89, in token_str_expired 
   options={"verify_signature": False, "verify_aud": False, "verify_exp": True, "verify_nbf": True}, 
 File "/usr/lib/python3.6/site-packages/jwt/api_jwt.py", line 69, in decode 
   payload, signing_input, header, signature = self._load(jwt) 
 File "/usr/lib/python3.6/site-packages/jwt/api_jws.py", line 174, in _load 
   raise DecodeError('Invalid header padding') 
jwt.exceptions.DecodeError: Invalid header padding 
[2022-08-26 15:51:32,062] WARNING: Credential file /etc/gwms-frontend/plugin.d/scitokens_callout.py is expired, skipping
```

**To Reproduce**
Here's the generator configuration that produces the error:
`<credential generator="scitokens_callout" absfname="/etc/gwms-frontend/plugin.d/scitokens_callout" security_class="frontend" trust_domain="grid" type="scitoken"/>`

**Expected behavior**
The generator should be used to renew and provide valid SciTokens.

**Desktop (please complete the following information):**

-   GlideinWMS version: 3.9.6-0.2.rc2.osg36.el8
-   Python version: Python 3.6
-   OS version: EL8
-   HTCondor version: ?

**Comment by mambelli** [comment]
Fixed
