### ISSUE TITLE
Frontend config error on python 3.9. with alma 9

### ISSUE THREAD

**Issue by namrathaurs** [glideinWMS/glideinwms#299]
Following are the details as reported by Steven Timm:

```
Info: Uploading facts for hepcintfe01.fnal.gov to ssi-puppet.fnal.gov
[root@hepcintfe01 ~]# gwms-frontend upgrade
Using default frontend config file: /etc/gwms-frontend/frontend.xml
All connected Factories are at least v3.4.1
NOTE: Python 3 has stricter type restrictions which may cause match expressions to fail in execution time. Please, make sure match_attr types are appropriately defined.
Traceback (most recent call last):
  File "/sbin/reconfig_frontend", line 196, in <module>
    p3_compatible, report = check_python3_expr.main(xml, False, True)
  File "/usr/lib/python3.9/site-packages/glideinwms/creation/lib/check_python3_expr.py", line 212, in main
    for element in findall_path(tree.getroot(), "match"):
  File "/usr/lib/python3.9/site-packages/glideinwms/creation/lib/check_python3_expr.py", line 126, in findall_path
    for child in element.data.getchildren():
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
Upgrading the frontend                                     [FAILED]
```

The suspicion was presumably that the frontend does not like one of the MatchExprs in the frontend.xml, but the error message does not clearly state which MatchExpr might be troublesome. If it is that, how can the troublesome MatchExpr be identified? (The frontend.xml file was attached via email to glideinwms-support mailing list).

**Comment by namrathaurs** [comment]
PR #302 fixes this issue and the patching instructions for GlideinWMS 3.10.2 is available here - https://github.com/glideinWMS/glideinwms/pull/302#issuecomment-1568519558
