### ISSUE TITLE
structlog issue on el7 release

### ISSUE THREAD

**Issue by mmascher** [glideinWMS/glideinwms#343]
**Describe the bug**
Reconfigure fails likely because of a wrong version of structlog is installed on el7. See the stacktrace below.

**To Reproduce**
Just reconfigure the factory on el7

**Screenshots**
```
[mmascher@vocms0205 ~]$ sudo gwms-factory reconfig
Using default factory config file: /etc/gwms-factory/glideinWMS.xml
Reconfiguring the factory... 
Traceback (most recent call last):
  File "/sbin/reconfig_glidein", line 24, in <module>
    from glideinwms.factory import glideFactoryConfig, glideFactoryLib, glideFactoryMonitorAggregator
  File "/usr/lib/python3.6/site-packages/glideinwms/factory/glideFactoryLib.py", line 33, in <module>
    from glideinwms.lib import (
  File "/usr/lib/python3.6/site-packages/glideinwms/lib/condorExe.py", line 10, in <module>
    from . import logSupport, subprocessSupport
  File "/usr/lib/python3.6/site-packages/glideinwms/lib/logSupport.py", line 418, in <module>
    structlog.processors.CallsiteParameterAdder(
AttributeError: module 'structlog.processors' has no attribute 'CallsiteParameterAdder'
Factory reconfiguration...                                 [FAILED]
[mmascher@vocms0205 ~]$ sudo vim /usr/lib/python3.6/site-packages/glideinwms/lib/logSupport.py
[mmascher@vocms0205 ~]$ sudo vim /usr/lib/python3.6/site-packages/glideinwms/lib/logSupport.py
[mmascher@vocms0205 ~]$ python3 
Python 3.6.8 (default, Jun 20 2023, 11:53:23) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import structlog
>>> structlog.__version__
'17.2.0'
>>> 
```

**Info (please complete the following information):**

-   GlideinWMS version: 3.10.3.rc2
-   OS version: el7
-   Priority: critical
-   Stakeholders: all
-   Components: factory

**Comment by brianhlin** [comment]
This also affects the frontend

```
Using default frontend config file: /etc/gwms-frontend/frontend.xml
Traceback (most recent call last):
  File "/sbin/reconfig_frontend", line 20, in <module>
    from glideinwms.creation.lib import (
  File "/usr/lib/python3.6/site-packages/glideinwms/creation/lib/cvWCreate.py", line 21, in <module>
    from glideinwms.lib import condorExe, condorSecurity
  File "/usr/lib/python3.6/site-packages/glideinwms/lib/condorExe.py", line 10, in <module>
    from . import logSupport, subprocessSupport
  File "/usr/lib/python3.6/site-packages/glideinwms/lib/logSupport.py", line 417, in <module>
    structlog.processors.CallsiteParameterAdder(
AttributeError: module 'structlog.processors' has no attribute 'CallsiteParameterAdder'
Upgrading the frontend[FAILED]
```
