### ISSUE TITLE
Fix glidein_status

### ISSUE THREAD

**Issue by mambelli** [glideinWMS/glideinwms#422]
**Describe the bug**
An error (stack trace) occurs when invoking glidein_status in the Factory
```
$ glidein_status
WARNING: GSI authentication is enabled by your security configuration! GSI is no longer supported.
For details, see https://htcondor.org/news/plan-to-replace-gst-in-htcss/
Traceback (most recent call last):
  File "/usr/bin/glidein_status", line 415, in <module>
    main()
  File "/usr/bin/glidein_status", line 258, in main
    keys.sort(machine_cmp)
TypeError: sort() takes no positional arguments
```
**To Reproduce**
Invoke glidein_status in the Factory

**Expected behavior**
No stack trace

**Screenshots**
NA

**Info (please complete the following information):**
Stakeholders and components can be a comma separated list or on multiple lines.
If you add a new stakeholder or component, not on the sample list, add it on a line by its own.

-   GlideinWMS version: 3.10.7
-   Python version: 3.9
-   OS version: Alma9
-   HTCondor version: 23
-   Priority: medium
-   Stakeholders: Fermilab
-   Components: factory

**Additional context**
NA

**Comment by namrathaurs** [comment]
Asked the stakeholders of GlideinWMS regarding the usage of this tool and the team was informed that this tool has not been significantly used.


Resolution involves ensuring the existing code is compatible with python 3.9 since `sort()` functionality has changed between Python 2 and Python 3.
* `sort` in python 2, we could pass a function that returns a boolean
* `sort` in python 3, comparison function was removed and a key can be returned which can be an element or a function, that is used by the sort function
